name: Scheduled Python Script Run
on:
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight UTC
  workflow_dispatch:  # This allows manual triggering
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install websockets
      continue-on-error: true
    - name: Run script
      run: python Websocket_10Bets.py
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: script-output
        path: output.txt
      if: always()
    - name: Check for script output
      run: |
        if [ ! -f output.txt ]; then
          echo "output.txt was not created. The script may have failed."
          exit 1
        fi
      if: always()
    - name: Post to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: |
          Workflow: ${{ github.workflow }}
          Status: ${{ job.status }}
          ${{ github.event_name == 'workflow_dispatch' && 'Manually triggered' || 'Scheduled run' }}
          ${{ github.event.head_commit.message }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()  # This ensures the Slack message is sent whether the job succeeds or fails
