name: Making One Bet
on:
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight UTC
  workflow_dispatch:  # This allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install websockets
      
      - name: Run script
        run: python Websocket.py
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.txt
        if: always()
      
      - name: Read output file
        id: read_output
        run: |
          if [ -f output.txt ]; then
            content=$(cat output.txt)
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            echo "content<<EOF" >> $GITHUB_OUTPUT
            echo "$content" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "content=No output.txt file found." >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Prepare Slack message
        id: slack_message
        run: |
          message=$(cat << EOF
          {
            "text": "Workflow: ${{ github.workflow }}\nStatus: ${{ job.status }}\n${{ github.event_name == 'workflow_dispatch' && 'Manually triggered' || 'Scheduled run' }}\n${{ github.event.head_commit.message }}\nOutput:\n\`\`\`${{ steps.read_output.outputs.content }}\`\`\`"
          }
          EOF
          )
          echo 'message<<EOF' >> $GITHUB_OUTPUT
          echo "$message" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Post to Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: ${{ steps.slack_message.outputs.message }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
